/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _maniLayoutRouteImport } from './routes/__maniLayout'
import { Route as _maniLayoutIndexRouteImport } from './routes/__maniLayout/index'
import { Route as _maniLayoutScaRouteImport } from './routes/__maniLayout/sca'
import { Route as _maniLayoutModuleRouteImport } from './routes/__maniLayout/module'
import { Route as _maniLayoutAsaRouteImport } from './routes/__maniLayout/asa'
import { Route as _maniLayoutAsaIndexRouteImport } from './routes/__maniLayout/asa/index'
import { Route as _maniLayoutScaStudentManagementRouteImport } from './routes/__maniLayout/sca/student-management'
import { Route as _maniLayoutScaHomeRouteImport } from './routes/__maniLayout/sca/home'
import { Route as _maniLayoutScaCourseManagementRouteImport } from './routes/__maniLayout/sca/course-management'
import { Route as _maniLayoutScaAllocationProcessingRouteImport } from './routes/__maniLayout/sca/allocation-processing'
import { Route as _maniLayoutScaAiAssistantRouteImport } from './routes/__maniLayout/sca/ai-assistant'
import { Route as _maniLayoutAsaSqlAssistantRouteImport } from './routes/__maniLayout/asa/sql-assistant'
import { Route as _maniLayoutAsaSchemaDetectionRouteImport } from './routes/__maniLayout/asa/schema-detection'
import { Route as _maniLayoutAsaHomeRouteImport } from './routes/__maniLayout/asa/home'
import { Route as _maniLayoutAsaDynamicTableCreationRouteImport } from './routes/__maniLayout/asa/dynamic-table-creation'
import { Route as _maniLayoutAsaDatasetUploadRouteImport } from './routes/__maniLayout/asa/dataset-upload'

const _maniLayoutRoute = _maniLayoutRouteImport.update({
  id: '/__maniLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _maniLayoutIndexRoute = _maniLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _maniLayoutRoute,
} as any)
const _maniLayoutScaRoute = _maniLayoutScaRouteImport.update({
  id: '/sca',
  path: '/sca',
  getParentRoute: () => _maniLayoutRoute,
} as any)
const _maniLayoutModuleRoute = _maniLayoutModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => _maniLayoutRoute,
} as any)
const _maniLayoutAsaRoute = _maniLayoutAsaRouteImport.update({
  id: '/asa',
  path: '/asa',
  getParentRoute: () => _maniLayoutRoute,
} as any)
const _maniLayoutAsaIndexRoute = _maniLayoutAsaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _maniLayoutAsaRoute,
} as any)
const _maniLayoutScaStudentManagementRoute =
  _maniLayoutScaStudentManagementRouteImport.update({
    id: '/student-management',
    path: '/student-management',
    getParentRoute: () => _maniLayoutScaRoute,
  } as any)
const _maniLayoutScaHomeRoute = _maniLayoutScaHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _maniLayoutScaRoute,
} as any)
const _maniLayoutScaCourseManagementRoute =
  _maniLayoutScaCourseManagementRouteImport.update({
    id: '/course-management',
    path: '/course-management',
    getParentRoute: () => _maniLayoutScaRoute,
  } as any)
const _maniLayoutScaAllocationProcessingRoute =
  _maniLayoutScaAllocationProcessingRouteImport.update({
    id: '/allocation-processing',
    path: '/allocation-processing',
    getParentRoute: () => _maniLayoutScaRoute,
  } as any)
const _maniLayoutScaAiAssistantRoute =
  _maniLayoutScaAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => _maniLayoutScaRoute,
  } as any)
const _maniLayoutAsaSqlAssistantRoute =
  _maniLayoutAsaSqlAssistantRouteImport.update({
    id: '/sql-assistant',
    path: '/sql-assistant',
    getParentRoute: () => _maniLayoutAsaRoute,
  } as any)
const _maniLayoutAsaSchemaDetectionRoute =
  _maniLayoutAsaSchemaDetectionRouteImport.update({
    id: '/schema-detection',
    path: '/schema-detection',
    getParentRoute: () => _maniLayoutAsaRoute,
  } as any)
const _maniLayoutAsaHomeRoute = _maniLayoutAsaHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _maniLayoutAsaRoute,
} as any)
const _maniLayoutAsaDynamicTableCreationRoute =
  _maniLayoutAsaDynamicTableCreationRouteImport.update({
    id: '/dynamic-table-creation',
    path: '/dynamic-table-creation',
    getParentRoute: () => _maniLayoutAsaRoute,
  } as any)
const _maniLayoutAsaDatasetUploadRoute =
  _maniLayoutAsaDatasetUploadRouteImport.update({
    id: '/dataset-upload',
    path: '/dataset-upload',
    getParentRoute: () => _maniLayoutAsaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof _maniLayoutIndexRoute
  '/asa': typeof _maniLayoutAsaRouteWithChildren
  '/module': typeof _maniLayoutModuleRoute
  '/sca': typeof _maniLayoutScaRouteWithChildren
  '/asa/dataset-upload': typeof _maniLayoutAsaDatasetUploadRoute
  '/asa/dynamic-table-creation': typeof _maniLayoutAsaDynamicTableCreationRoute
  '/asa/home': typeof _maniLayoutAsaHomeRoute
  '/asa/schema-detection': typeof _maniLayoutAsaSchemaDetectionRoute
  '/asa/sql-assistant': typeof _maniLayoutAsaSqlAssistantRoute
  '/sca/ai-assistant': typeof _maniLayoutScaAiAssistantRoute
  '/sca/allocation-processing': typeof _maniLayoutScaAllocationProcessingRoute
  '/sca/course-management': typeof _maniLayoutScaCourseManagementRoute
  '/sca/home': typeof _maniLayoutScaHomeRoute
  '/sca/student-management': typeof _maniLayoutScaStudentManagementRoute
  '/asa/': typeof _maniLayoutAsaIndexRoute
}
export interface FileRoutesByTo {
  '/module': typeof _maniLayoutModuleRoute
  '/sca': typeof _maniLayoutScaRouteWithChildren
  '/': typeof _maniLayoutIndexRoute
  '/asa/dataset-upload': typeof _maniLayoutAsaDatasetUploadRoute
  '/asa/dynamic-table-creation': typeof _maniLayoutAsaDynamicTableCreationRoute
  '/asa/home': typeof _maniLayoutAsaHomeRoute
  '/asa/schema-detection': typeof _maniLayoutAsaSchemaDetectionRoute
  '/asa/sql-assistant': typeof _maniLayoutAsaSqlAssistantRoute
  '/sca/ai-assistant': typeof _maniLayoutScaAiAssistantRoute
  '/sca/allocation-processing': typeof _maniLayoutScaAllocationProcessingRoute
  '/sca/course-management': typeof _maniLayoutScaCourseManagementRoute
  '/sca/home': typeof _maniLayoutScaHomeRoute
  '/sca/student-management': typeof _maniLayoutScaStudentManagementRoute
  '/asa': typeof _maniLayoutAsaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__maniLayout': typeof _maniLayoutRouteWithChildren
  '/__maniLayout/asa': typeof _maniLayoutAsaRouteWithChildren
  '/__maniLayout/module': typeof _maniLayoutModuleRoute
  '/__maniLayout/sca': typeof _maniLayoutScaRouteWithChildren
  '/__maniLayout/': typeof _maniLayoutIndexRoute
  '/__maniLayout/asa/dataset-upload': typeof _maniLayoutAsaDatasetUploadRoute
  '/__maniLayout/asa/dynamic-table-creation': typeof _maniLayoutAsaDynamicTableCreationRoute
  '/__maniLayout/asa/home': typeof _maniLayoutAsaHomeRoute
  '/__maniLayout/asa/schema-detection': typeof _maniLayoutAsaSchemaDetectionRoute
  '/__maniLayout/asa/sql-assistant': typeof _maniLayoutAsaSqlAssistantRoute
  '/__maniLayout/sca/ai-assistant': typeof _maniLayoutScaAiAssistantRoute
  '/__maniLayout/sca/allocation-processing': typeof _maniLayoutScaAllocationProcessingRoute
  '/__maniLayout/sca/course-management': typeof _maniLayoutScaCourseManagementRoute
  '/__maniLayout/sca/home': typeof _maniLayoutScaHomeRoute
  '/__maniLayout/sca/student-management': typeof _maniLayoutScaStudentManagementRoute
  '/__maniLayout/asa/': typeof _maniLayoutAsaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asa'
    | '/module'
    | '/sca'
    | '/asa/dataset-upload'
    | '/asa/dynamic-table-creation'
    | '/asa/home'
    | '/asa/schema-detection'
    | '/asa/sql-assistant'
    | '/sca/ai-assistant'
    | '/sca/allocation-processing'
    | '/sca/course-management'
    | '/sca/home'
    | '/sca/student-management'
    | '/asa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/module'
    | '/sca'
    | '/'
    | '/asa/dataset-upload'
    | '/asa/dynamic-table-creation'
    | '/asa/home'
    | '/asa/schema-detection'
    | '/asa/sql-assistant'
    | '/sca/ai-assistant'
    | '/sca/allocation-processing'
    | '/sca/course-management'
    | '/sca/home'
    | '/sca/student-management'
    | '/asa'
  id:
    | '__root__'
    | '/__maniLayout'
    | '/__maniLayout/asa'
    | '/__maniLayout/module'
    | '/__maniLayout/sca'
    | '/__maniLayout/'
    | '/__maniLayout/asa/dataset-upload'
    | '/__maniLayout/asa/dynamic-table-creation'
    | '/__maniLayout/asa/home'
    | '/__maniLayout/asa/schema-detection'
    | '/__maniLayout/asa/sql-assistant'
    | '/__maniLayout/sca/ai-assistant'
    | '/__maniLayout/sca/allocation-processing'
    | '/__maniLayout/sca/course-management'
    | '/__maniLayout/sca/home'
    | '/__maniLayout/sca/student-management'
    | '/__maniLayout/asa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _maniLayoutRoute: typeof _maniLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__maniLayout': {
      id: '/__maniLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _maniLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__maniLayout/': {
      id: '/__maniLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _maniLayoutIndexRouteImport
      parentRoute: typeof _maniLayoutRoute
    }
    '/__maniLayout/sca': {
      id: '/__maniLayout/sca'
      path: '/sca'
      fullPath: '/sca'
      preLoaderRoute: typeof _maniLayoutScaRouteImport
      parentRoute: typeof _maniLayoutRoute
    }
    '/__maniLayout/module': {
      id: '/__maniLayout/module'
      path: '/module'
      fullPath: '/module'
      preLoaderRoute: typeof _maniLayoutModuleRouteImport
      parentRoute: typeof _maniLayoutRoute
    }
    '/__maniLayout/asa': {
      id: '/__maniLayout/asa'
      path: '/asa'
      fullPath: '/asa'
      preLoaderRoute: typeof _maniLayoutAsaRouteImport
      parentRoute: typeof _maniLayoutRoute
    }
    '/__maniLayout/asa/': {
      id: '/__maniLayout/asa/'
      path: '/'
      fullPath: '/asa/'
      preLoaderRoute: typeof _maniLayoutAsaIndexRouteImport
      parentRoute: typeof _maniLayoutAsaRoute
    }
    '/__maniLayout/sca/student-management': {
      id: '/__maniLayout/sca/student-management'
      path: '/student-management'
      fullPath: '/sca/student-management'
      preLoaderRoute: typeof _maniLayoutScaStudentManagementRouteImport
      parentRoute: typeof _maniLayoutScaRoute
    }
    '/__maniLayout/sca/home': {
      id: '/__maniLayout/sca/home'
      path: '/home'
      fullPath: '/sca/home'
      preLoaderRoute: typeof _maniLayoutScaHomeRouteImport
      parentRoute: typeof _maniLayoutScaRoute
    }
    '/__maniLayout/sca/course-management': {
      id: '/__maniLayout/sca/course-management'
      path: '/course-management'
      fullPath: '/sca/course-management'
      preLoaderRoute: typeof _maniLayoutScaCourseManagementRouteImport
      parentRoute: typeof _maniLayoutScaRoute
    }
    '/__maniLayout/sca/allocation-processing': {
      id: '/__maniLayout/sca/allocation-processing'
      path: '/allocation-processing'
      fullPath: '/sca/allocation-processing'
      preLoaderRoute: typeof _maniLayoutScaAllocationProcessingRouteImport
      parentRoute: typeof _maniLayoutScaRoute
    }
    '/__maniLayout/sca/ai-assistant': {
      id: '/__maniLayout/sca/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/sca/ai-assistant'
      preLoaderRoute: typeof _maniLayoutScaAiAssistantRouteImport
      parentRoute: typeof _maniLayoutScaRoute
    }
    '/__maniLayout/asa/sql-assistant': {
      id: '/__maniLayout/asa/sql-assistant'
      path: '/sql-assistant'
      fullPath: '/asa/sql-assistant'
      preLoaderRoute: typeof _maniLayoutAsaSqlAssistantRouteImport
      parentRoute: typeof _maniLayoutAsaRoute
    }
    '/__maniLayout/asa/schema-detection': {
      id: '/__maniLayout/asa/schema-detection'
      path: '/schema-detection'
      fullPath: '/asa/schema-detection'
      preLoaderRoute: typeof _maniLayoutAsaSchemaDetectionRouteImport
      parentRoute: typeof _maniLayoutAsaRoute
    }
    '/__maniLayout/asa/home': {
      id: '/__maniLayout/asa/home'
      path: '/home'
      fullPath: '/asa/home'
      preLoaderRoute: typeof _maniLayoutAsaHomeRouteImport
      parentRoute: typeof _maniLayoutAsaRoute
    }
    '/__maniLayout/asa/dynamic-table-creation': {
      id: '/__maniLayout/asa/dynamic-table-creation'
      path: '/dynamic-table-creation'
      fullPath: '/asa/dynamic-table-creation'
      preLoaderRoute: typeof _maniLayoutAsaDynamicTableCreationRouteImport
      parentRoute: typeof _maniLayoutAsaRoute
    }
    '/__maniLayout/asa/dataset-upload': {
      id: '/__maniLayout/asa/dataset-upload'
      path: '/dataset-upload'
      fullPath: '/asa/dataset-upload'
      preLoaderRoute: typeof _maniLayoutAsaDatasetUploadRouteImport
      parentRoute: typeof _maniLayoutAsaRoute
    }
  }
}

interface _maniLayoutAsaRouteChildren {
  _maniLayoutAsaDatasetUploadRoute: typeof _maniLayoutAsaDatasetUploadRoute
  _maniLayoutAsaDynamicTableCreationRoute: typeof _maniLayoutAsaDynamicTableCreationRoute
  _maniLayoutAsaHomeRoute: typeof _maniLayoutAsaHomeRoute
  _maniLayoutAsaSchemaDetectionRoute: typeof _maniLayoutAsaSchemaDetectionRoute
  _maniLayoutAsaSqlAssistantRoute: typeof _maniLayoutAsaSqlAssistantRoute
  _maniLayoutAsaIndexRoute: typeof _maniLayoutAsaIndexRoute
}

const _maniLayoutAsaRouteChildren: _maniLayoutAsaRouteChildren = {
  _maniLayoutAsaDatasetUploadRoute: _maniLayoutAsaDatasetUploadRoute,
  _maniLayoutAsaDynamicTableCreationRoute:
    _maniLayoutAsaDynamicTableCreationRoute,
  _maniLayoutAsaHomeRoute: _maniLayoutAsaHomeRoute,
  _maniLayoutAsaSchemaDetectionRoute: _maniLayoutAsaSchemaDetectionRoute,
  _maniLayoutAsaSqlAssistantRoute: _maniLayoutAsaSqlAssistantRoute,
  _maniLayoutAsaIndexRoute: _maniLayoutAsaIndexRoute,
}

const _maniLayoutAsaRouteWithChildren = _maniLayoutAsaRoute._addFileChildren(
  _maniLayoutAsaRouteChildren,
)

interface _maniLayoutScaRouteChildren {
  _maniLayoutScaAiAssistantRoute: typeof _maniLayoutScaAiAssistantRoute
  _maniLayoutScaAllocationProcessingRoute: typeof _maniLayoutScaAllocationProcessingRoute
  _maniLayoutScaCourseManagementRoute: typeof _maniLayoutScaCourseManagementRoute
  _maniLayoutScaHomeRoute: typeof _maniLayoutScaHomeRoute
  _maniLayoutScaStudentManagementRoute: typeof _maniLayoutScaStudentManagementRoute
}

const _maniLayoutScaRouteChildren: _maniLayoutScaRouteChildren = {
  _maniLayoutScaAiAssistantRoute: _maniLayoutScaAiAssistantRoute,
  _maniLayoutScaAllocationProcessingRoute:
    _maniLayoutScaAllocationProcessingRoute,
  _maniLayoutScaCourseManagementRoute: _maniLayoutScaCourseManagementRoute,
  _maniLayoutScaHomeRoute: _maniLayoutScaHomeRoute,
  _maniLayoutScaStudentManagementRoute: _maniLayoutScaStudentManagementRoute,
}

const _maniLayoutScaRouteWithChildren = _maniLayoutScaRoute._addFileChildren(
  _maniLayoutScaRouteChildren,
)

interface _maniLayoutRouteChildren {
  _maniLayoutAsaRoute: typeof _maniLayoutAsaRouteWithChildren
  _maniLayoutModuleRoute: typeof _maniLayoutModuleRoute
  _maniLayoutScaRoute: typeof _maniLayoutScaRouteWithChildren
  _maniLayoutIndexRoute: typeof _maniLayoutIndexRoute
}

const _maniLayoutRouteChildren: _maniLayoutRouteChildren = {
  _maniLayoutAsaRoute: _maniLayoutAsaRouteWithChildren,
  _maniLayoutModuleRoute: _maniLayoutModuleRoute,
  _maniLayoutScaRoute: _maniLayoutScaRouteWithChildren,
  _maniLayoutIndexRoute: _maniLayoutIndexRoute,
}

const _maniLayoutRouteWithChildren = _maniLayoutRoute._addFileChildren(
  _maniLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _maniLayoutRoute: _maniLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
